# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b3a95ecaa77bddab4214e2058f2ff00283d7b11d69efc3ff1a886e79060956e6bc850ac508c15ede85d00347aa9727edbdbf0b29b7040c47c5f82369dec90a7

test:
  secret_key_base: a938a5a505e3ff9cfcd6b7f854006f12f9a70a2a40b58f19dfff228e2f04a07421d113af827f0d1523836c72d25d16db286eace838cfb737621863d2deb15292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
