#Create all neighborhood affiliated with downtown Charleston
Neighborhood.create(title: "Ansonborough")
Neighborhood.create(title: "Cannonborough")
Neighborhood.create(title: "Eastside")
Neighborhood.create(title: "French Quarter")
Neighborhood.create(title: "Hampton Park Terrace")
Neighborhood.create(title: "Harleston Village")
Neighborhood.create(title: "King Street")
Neighborhood.create(title: "Mazyck-Wraggborough")
Neighborhood.create(title: "North Central")
Neighborhood.create(title: "Radcliffborough")
Neighborhood.create(title: "South of Broad")
Neighborhood.create(title: "Wagener Terrace")
Neighborhood.create(title: "Westside")


#Create categories visible on yelp
Category.create(type: "Restaurants")
Category.create(type: "Food")
Category.create(type: "Nightlife")
Category.create(type: "Bars")
Category.create(type: "Sandwiches")
Category.create(type: "American (Traditional)")
Category.create(type: "Breakfast & Brunch")
Category.create(type: "Seafood")
Category.create(type: "Pizza")
Category.create(type: "Fast Food")
Category.create(type: "American (New)")
Category.create(type: "Burgers")
Category.create(type: "Salad")
Category.create(type: "Mexican")
Category.create(type: "Coffee & Tea")
Category.create(type: "Southern")
Category.create(type: "Italian")
Category.create(type: "Cafes")
Category.create(type: "Delis")
Category.create(type: "Chinese")
Category.create(type: "Barbeque")
Category.create(type: "Chicken Wings")
Category.create(type: "Japanese")
Category.create(type: "Sports Bars")
Category.create(type: "Bakeries")
Category.create(type: "Sushi Bars")
Category.create(type: "Specialty Food")
Category.create(type: "Diners")
Category.create(type: "Cocktail Bars")
Category.create(type: "Pubs")
Category.create(type: "Asian Fusion")
Category.create(type: "Thai")
Category.create(type: "Soup")
Category.create(type: "Beer Bar")
Category.create(type: "Mediterranean")
